apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hdfs-datanode
spec:
  selector:
    matchLabels:
      name: hdfs-datanode
  template:
    metadata:
      labels:
        name: hdfs-datanode
    spec:
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: datanode
          image: uhopper/hadoop-datanode:2.7.2
          env:
            - name: HADOOP_CUSTOM_CONF_DIR
              value: /etc/hadoop-custom-conf
            - name: MULTIHOMED_NETWORK
              value: "0"
            {{- if and .Values.kerberosEnabled .Values.jsvcEnabled }}
            - name: HADOOP_SECURE_DN_USER
              value: root
            - name: JSVC_OUTFILE
              value: /dev/stdout
            - name: JSVC_ERRFILE
              value: /dev/stderr
            - name: JSVC_HOME
              value: /jsvc-home
            {{- end }}
          livenessProbe:
            initialDelaySeconds: 30
            httpGet:
              host: 127.0.0.1
              path: /
              {{- if and .Values.kerberosEnabled .Values.jsvcEnabled }}
              port: 1006
              {{- else }}
              port: 50075
              {{- end }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: hdfs-config
              mountPath: /etc/hadoop-custom-conf
              readOnly: true
            - name: hdfs-data
              mountPath: /hadoop
            {{- if .Values.kerberosEnabled }}
            - name: kerberos-config
              mountPath: /etc/krb5.conf
              subPath: {{ .Values.kerberosConfigFileName }}
              readOnly: true
            - name: kerberos-keytab-copy
              mountPath: /etc/security/
              readOnly: true
            {{- if .Values.jsvcEnabled }}
            - name: jsvc-home
              mountPath: /jsvc-home
            {{- end }}
            {{- end }}
      {{- if .Values.kerberosEnabled }}
      initContainers:
        - name: copy-kerberos-keytab
          image: busybox:1.27.1
          command: ['sh', '-c']
          args:
            - cp /kerberos-keytabs/$MY_NODE_NAME.keytab /kerberos-keytab-copy/hdfs.keytab
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: kerberos-keytabs
              mountPath: /kerberos-keytabs
            - name: kerberos-keytab-copy
              mountPath: /kerberos-keytab-copy
        {{- if .Values.jsvcEnabled }}
        - name: copy-jsvc
          # Pull by digest because the image doesn't have tags to pin.
          image: mschlimb/jsvc@sha256:bf20eb9a319e9a2f87473d8da7418d21503a97528b932800b6b8417cd31e30ef
          command: ['sh', '-c']
          args:
            - cp /usr/bin/jsvc /jsvc-home/jsvc
          volumeMounts:
            - name: jsvc-home
              mountPath: /jsvc-home
        {{- end }}
      {{- end }}
      restartPolicy: Always
      volumes:
        - name: hdfs-data
          hostPath:
            path: {{ .Values.dataNodeHostPath }}
        - name: hdfs-config
          configMap:
            name: {{ .Values.hdfsConfigMap }}
        {{- if .Values.kerberosEnabled }}
        - name: kerberos-config
          configMap:
            name: {{ .Values.kerberosConfigMap }}
        - name: kerberos-keytabs
          secret:
            secretName: {{ .Values.kerberosKeytabsSecret }}
        - name: kerberos-keytab-copy
          emptyDir: {}
        {{- if .Values.jsvcEnabled }}
        - name: jsvc-home
          emptyDir: {}
        {{- end }}
        {{- end }}
